/**
    THIS SCRIPT, BUILDS THE CLINICA DATABASE 
    BUILDS 6 TABLES, THAT BELONGS TO THE CLINICA DATABASE
    
    
    PATIENT:
        ID
        NAME
        LASTNAME
        DNI
        BIRTHDATE
        GENDER (WOMEN,MAN)
        ADDRESS
        TELEPHONE
        EMAIL
        OTHER DEAILS
    
    DOCTOR:
        ID
        NAME
        LASTNAME
        DNI --> UNIQUE
        ESPECIALTY
        TELEPHONE
        EMAIL
        CONSULTATION DATE
        OTHER_CREDENTIAL
        
    APPOINTMENT
        ID
        ID_PATIENT
        ID_DOCTOR
        APPOINTMENT_DATE
        APPOINTMENT_REASON
        APPOINTMENT_DATE(CONFIRMED,CANCEL,COMPLETED)
    
    HISTORICAL
        ID
        ID_PATIENT
        VISIT_DATE
        DIAGNOSIS
        TREATMENT
        RECOMENDEDS
        RESULTS
    
    MEDICINE
        ID
        MEDICINE_NAME
        DESCRIPTION
        INSTRUCTIONS
        
    PRESCRIPTION
        ID
        ID_PATIENT
        ID_MEDICINE
        PRESCRIPTION_DATE
        DOSE
        INSTRUCTIONS
*/

CREATE TABLE PATIENT(
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    LASTNAME VARCHAR2(20) NOT NULL,
    DNI NUMBER(9) UNIQUE NOT NULL,
    BIRTHDATE DATE NOT NULL,
    GENDER VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(30),
    TELEPHONE INTEGER NOT NULL,
    EMAIL VARCHAR2(40) ,
    OTHER_DETAILS CLOB
);


CREATE TABLE DOCTOR(
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    LASTNAME VARCHAR2(20) NOT NULL,
    DNI number(9) UNIQUE NOT NULL,
    ESPECIALITY VARCHAR2(20) NOT NULL,
    TELEPHONE INTEGER NOT NULL,
    EMAIL VARCHAR2(30),
    CONSULTATION_DATE DATE NOT NULL,
    OTHER_CREDENTIAL CLOB
);

CREATE TABLE APPOINTMENT(
    ID INTEGER PRIMARY KEY,
    ID_PATIENT INTEGER,
    ID_DOCTOR INTEGER,
    APPOINTMENT_DATE DATE NOT NULL,
    APPOINTMENT_REASON VARCHAR2(30) NOT NULL,
    APPOINTMENT_STATUS VARCHAR2(20) NOT NULL,
    FOREIGN KEY (ID_PATIENT) REFERENCES PATIENT(ID),
    FOREIGN KEY (ID_DOCTOR) REFERENCES DOCTOR(ID)
);

CREATE TABLE HISTORICAL(
  ID INTEGER PRIMARY KEY,
  ID_PATIENT INTEGER,
  VISIT_DATE DATE NOT NULL ,
  DIAGNOSIS VARCHAR2(30) NOT NULL,
  TREATMENT VARCHAR(30) NOT NULL,
  RECOMENDEDS CLOB NOT NULL,
  RESULTS CLOB NOT NULL ,
  FOREIGN KEY (ID_PATIENT) REFERENCES PATIENT(ID)
);

CREATE TABLE MEDICINE(
    ID INTEGER PRIMARY KEY,
    MEDICINE_NAME VARCHAR2(20) NOT NULL,
    DESCRIPTION CLOB NOT NULL,
    INSTRUCTION CLOB NOT NULL
);

CREATE TABLE PRESCRIPTION(
    ID INTEGER PRIMARY KEY,
    ID_PATIENT INTEGER,
    ID_MEDICINE INTEGER,
    PRESCRIPTION_DATE DATE,
    DOSE VARCHAR2(15),
    INSTRUCTIONS CLOB,
    FOREIGN KEY (ID_PATIENT) REFERENCES PATIENT(ID),
    FOREIGN KEY (ID_MEDICINE) REFERENCES MEDICINE(ID)
);

CREATE TABLE CONTROL(
    ID INTEGER PRIMARY KEY,
    EVENT VARCHAR2(10), 
    EVENT_DATE DATE
);




