create or replace TRIGGER PHONE_CONTROL
BEFORE INSERT OR UPDATE
ON PATIENT
FOR EACH ROW
DECLARE
    TELEPHONE NUMBER;
BEGIN

   TELEPHONE := TO_NUMBER(:NEW.TELEPHONE);

EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('ERROR');
       -- RAISE_APPLICATION_ERROR(-20001,'THE TELEPHONE NUMBER IS NOT NUMBER TYPE');
END;


delete from patient;

alter table patient modify telephone varchar2(30);